# Generated by Django 5.1.15 on 2026-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=120, unique=True)),
                ('part', models.CharField(choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2'), ('Part 3', 'Part 3')], max_length=10)),
                ('part_label', models.CharField(default='Question', max_length=120)),
                ('question', models.TextField()),
                ('prep_seconds', models.PositiveIntegerField(default=5)),
                ('speak_seconds', models.PositiveIntegerField(default=30)),
                ('image_src', models.CharField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('cue_points', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
