# Generated by Django 5.1.15 on 2026-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_src',
            field=models.TextField(blank=True),
        ),
    ]
