# Generated by Django 5.1.15 on 2026-06-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_reference_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='against_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='for_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
