# Generated by Django 5.1.15 on 2026-06-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_against_points_question_for_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
